const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {firefox}=require('playwright');
const route=path.join(__dirname,'..','sketches','release-ui-overhaul','06-five-slot-badges');
const types={'.html':'text/html','.js':'text/javascript','.webmanifest':'application/manifest+json','.png':'image/png','.woff2':'font/woff2'};
const serve=()=>new Promise(resolve=>{const server=http.createServer((request,response)=>{try{const url=new URL(request.url,'http://127.0.0.1'),relative=decodeURIComponent(url.pathname).replace(/^\/+/,''),candidate=path.join(route,relative||'index.html');if(!candidate.startsWith(route+path.sep))throw new Error('invalid path');const stat=fs.statSync(candidate),file=stat.isDirectory()?path.join(candidate,'index.html'):candidate;response.setHeader('content-type',types[path.extname(file)]||'application/octet-stream');response.setHeader('cache-control','no-store');response.end(fs.readFileSync(file))}catch{response.statusCode=404;response.end('not found')}});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))});

test('narrow laptop phone and iPhone layouts match the Alarm reference without clipping',async()=>{
 const {server,origin}=await serve();let browser;
 try{browser=await firefox.launch({headless:true});for(const config of[{viewport:{width:363,height:719},hasTouch:false},{viewport:{width:331,height:690},hasTouch:true}])for(const theme of['light','dark']){
  const context=await browser.newContext({...config,colorScheme:theme});const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(String(error)));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});await page.addInitScript(()=>{const RealDate=Date;class FixedDate extends RealDate{constructor(...args){super(...(args.length?args:['2026-09-03T07:18:00-07:00']))}static now(){return new RealDate('2026-09-03T07:18:00-07:00').getTime()}}window.Date=FixedDate});
  await page.goto(`${origin}/index.html?theme=${theme}&screen=alarm&narrow-alarm=1`,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);
  const layout=await page.evaluate(()=>{const rect=e=>e.getBoundingClientRect(),phone=rect(document.querySelector('.phone')),screen=document.querySelector('[data-screen="alarm"]'),header=rect(document.querySelector('.alarm-head')),title=rect(document.querySelector('.alarm-head h1')),add=rect(document.getElementById('addAlarm')),rows=[...document.querySelectorAll('#alarmList .alarm-row')],rowRects=rows.map(rect),details=rows.map(row=>row.querySelector('.alarm-detail')),tab=rect(document.querySelector('.tabbar'));return{screenClient:screen.clientWidth,screenScroll:screen.scrollWidth,header:{left:header.left,right:header.right},title:{left:title.left,right:title.right,height:title.height,font:parseFloat(getComputedStyle(document.querySelector('.alarm-head h1')).fontSize)},add:{left:add.left,right:add.right,width:add.width},firstTop:rowRects[0].top-phone.top,rowRects:rowRects.map(r=>({left:r.left,right:r.right,width:r.width,height:r.height})),details:details.map(e=>({scroll:e.scrollWidth,client:e.clientWidth,text:e.textContent})),noteBottom:document.querySelector('.sleep-note').getBoundingClientRect().bottom,tabTop:tab.top}});
  assert.deepEqual(errors,[]);assert.equal(layout.screenScroll,layout.screenClient);assert.ok(layout.title.right<=layout.add.left-8,'title collides with Add');assert.ok(layout.add.right<=layout.header.right+.5,'Add escapes header');assert.ok(layout.add.width>=43.5);assert.ok(layout.title.font<=35);assert.ok(layout.firstTop<=145,'first card starts too low');assert.ok(layout.rowRects[0].height>=184&&layout.rowRects[0].height<=194);for(const row of layout.rowRects.slice(1))assert.ok(row.height>=92&&row.height<=100);for(const row of layout.rowRects)assert.ok(row.left>=layout.header.left-.5&&row.right<=layout.header.right+.5);for(const detail of layout.details)assert.ok(detail.scroll<=detail.client+1,`${detail.text} is clipped`);await page.locator('.sleep-note').scrollIntoViewIfNeeded();const noteClear=await page.evaluate(()=>document.querySelector('.sleep-note').getBoundingClientRect().bottom<=document.querySelector('.tabbar').getBoundingClientRect().top);assert.equal(noteClear,true,'alarm note cannot be brought above navigation');await context.close()
 }}finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}
});
