const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const html = fs.readFileSync(path.join(__dirname, '..', 'world.html'), 'utf8');
const serviceWorker = fs.readFileSync(path.join(__dirname, '..', 'service-worker.js'), 'utf8');

const cacheVersion = serviceWorker.match(/dreamworld-world-v(\d+)/)?.[1];
assert.ok(cacheVersion, 'service worker cache must be versioned');
for (const asset of ['dialogue-state.js', 'jungian-method.js', 'analysis-state.js', 'analysis-interview.js', 'analysis-dialogue.js', 'dream-scene.js', 'browser-transcriber.js']) {
  assert.match(html, new RegExp(`<script src="\\./${asset.replace('.', '\\.') }\\?v=${cacheVersion}"><\\/script>`), `${asset} must be cache-busted with the release version`);
  assert.match(serviceWorker, new RegExp(`\\./${asset.replace('.', '\\.') }\\?v=${cacheVersion}`), `${asset} must be cached under the same release-versioned URL`);
}
assert.match(html, /id="analysisView"[^>]+data-view="analysis"/);
assert.match(html, /Speak or type before it fades\./);
assert.match(html, /<details class="experimental-capture" id="experimentalCapture">\s*<summary>Voice &amp; transcription options<\/summary>/);
assert.doesNotMatch(html, /An unfinished draft stays in this browser/);
assert.match(html, /id="noDreamButton" class="capture-skip"/);
assert.match(html, /id="analysisBack"/);
assert.match(html, /id="analysisTitle"/);
assert.match(html, /id="analysisTranscript"/);
assert.match(html, />Your transcript</);
assert.match(html, /id="analysisCharacterName"/);
assert.match(html, /The Listener/);
assert.match(html, /class="analysis-game-scene"/, 'analysis should remain inside the game world');
assert.match(html, /id="analysisDialogueAdvance"/, 'the dialogue box should be the reveal and advance target');
assert.match(html, /id="analysisDialoguePage"/, 'dialogue should show page progress');
assert.match(html, /\.character-response\[data-complete="true"\][^{]+\{[^}]*display:\s*none/s, 'the continuation cue should disappear after the final page');
assert.match(html, /id="analysisDialogueStatus"[^>]+aria-live="polite"/, 'page completion should be announced without reading every typed character');
assert.match(html, /id="analysisTranscriptToggle"/, 'the transcript must remain available without dominating the scene');
assert.match(html, /id="analysisControlsToggle"/, 'privacy controls must remain reachable');
assert.match(html, /id="analysisFullOpen"[^>]+hidden/, 'full analysis stays hidden until the dialogue completes');
assert.match(html, /id="analysisFullPanel"[^>]+role="dialog"[^>]+aria-modal="true"[^>]+hidden/);
assert.match(html, /id="analysisFullText"/);
assert.match(html, /id="analysisTranscriptPanel"[^>]+role="dialog"[^>]+aria-modal="true"/);
assert.match(html, /id="analysisControlsPanel"[^>]+role="dialog"[^>]+aria-modal="true"/);
assert.match(html, /id="analysisCharacterResponse"[^>]+aria-live="off"/);
assert.match(html, /interpretive hypothesis, not a diagnosis or prediction/i);
assert.match(html, /DreamAnalysis\.createAnalysisSession/);
assert.match(html, /DreamAnalysis\.assessTranscriptEligibility\(dialogueFlow\.transcript\)/, 'logging must gate unclear text before persistence');
assert.match(html, /dataset\.action === 'edit-unclear'[\s\S]+saveDraft\(\)[\s\S]+logDream\(\)[\s\S]+showTranscriptionScene\(\)/, 'unclear audio must remain retryable before the user chooses editing');
assert.match(html, /DreamAnalysisDialogue\.paginateResponse/);
assert.match(html, /DreamAnalysisDialogue\.createTypewriterDialogue/);
assert.match(html, /DreamScene\.createDreamScene/);
assert.match(html, /id="analysisPreparation"[^>]+role="status"[^>]+aria-live="polite"[^>]+tabindex="-1"[^>]+hidden/, 'analysis preparation starts hidden, accepts programmatic focus, and announces stage changes');
assert.doesNotMatch(html, /id="analysisPreparation"[^>]+aria-busy/, 'stage announcements must not be suppressed behind aria-busy');
assert.match(html, /id="analysisPreparationTitle"/);
assert.match(html, /Reading your dream/);
assert.match(html, /Following the details/);
assert.match(html, /Preparing a reflection/);
assert.match(html, /const ANALYSIS_PREPARATION_DURATIONS = \[900, 950, 950\]/, 'production reflection pacing should be deliberate but bounded');
assert.match(html, /function startAnalysisPreparation\(dream\)/);
assert.match(html, /openAnalysis\(record\.id\)/, 'durable logging should enter the Listener interview');
assert.match(html, /function completeAnalysisInterview[\s\S]+startAnalysisPreparation\(dream\)/, 'reflection preparation should begin only after interview evidence exists');
assert.match(html, /id="analysisInterviewForm"[^>]+hidden/, 'the one-question answer form starts hidden');
assert.match(html, /id="analysisInterviewAnswer"[^>]+maxlength="600"/);
assert.match(html, /id="analysisInterviewFinish"[^>]+hidden>Reflect now/, 'the user may end the interview early after answering');
assert.match(html, /Your answers stay on this device/);
assert.match(html, /\.character-response\[data-typing="true"\][^{]+\.listener-mouth/s, 'the Listener portrait should visibly speak while text types');
assert.match(html, /data-scene/, 'the analysis view should expose its active dreamscape motif');
assert.match(html, /\.character-response\s*\{[^}]*border:\s*2px solid rgba[^}]*border:\s*2px solid color-mix[^}]*background:\s*linear-gradient\([^;]*rgba[^}]*background:\s*linear-gradient\([^;]*color-mix/s, 'the dialogue card needs readable fallbacks before enhanced color-mix styling');
assert.match(html, /maxCharacters:\s*280/, 'long reflections should use the reviewed adaptive page size');
assert.match(html, /characterResponse/);
assert.doesNotMatch(html, /window\.setTimeout\(\(\) => openAnalysis\(record\.id\), 220\)/, 'logging must no longer hard-cut directly to analysis');

assert.doesNotMatch(html, /Perspective families/);
assert.doesNotMatch(html, /analysisLensList/);
assert.doesNotMatch(html, /analysisAssociation/);
assert.doesNotMatch(html, /analysisWorkingMeaning/);
assert.doesNotMatch(html, /<(?:button|option)[^>]*>[^<]*(?:Freud|Jung|Plato|Aristotle|Descartes|Spinoza|Buddhist|Advaita|Zhuangzi)/i, 'the encounter must not offer philosopher or framework menus');

assert.match(html, /id="analysisDeleteReflection"/);
assert.match(html, /id="analysisRegenerateResponse"[^>]+hidden/);
assert.match(html, /id="analysisStorageDisclosure"/);
assert.match(html, /id="analysisMethodDisclosure"/);
assert.match(html, /id="analysisMethodSources"/);
assert.match(html, /Context-first Jungian reflection/i);
assert.match(html, /interpretive hypothesis/i);
assert.match(html, /CW 7[^<]*§§123–140/i);
assert.match(html, /id="analysisUndoDelete"[^>]+hidden/);
assert.match(html, /id="analysisKeepUndo"[^>]+hidden/);
assert.match(html, /id="analysisFinishDeletion"[^>]+hidden/);
assert.match(html, /interview answers and this response are saved in this browser without encryption/i);
assert.match(html, /this response could not be saved in browser storage/i);
assert.match(html, /saved response has been deleted/i);
assert.match(html, /\[hidden\]\s*\{\s*display:\s*none\s*!important/);
assert.match(html, /prefers-reduced-motion/);
assert.match(html, /\.character-copy[^}]+overflow-wrap:\s*anywhere/s);

const analysisSection = html.match(/<section class="view analysis-view"[\s\S]*?<\/section>\s*<section class="view capture-view"/i)?.[0] || '';
assert.ok(analysisSection.length > 0);
assert.match(analysisSection, /id="analysisTranscriptPanel"[^>]+hidden/, 'transcript starts behind a quiet game HUD action');
assert.match(analysisSection, /id="analysisControlsPanel"[^>]+hidden/, 'privacy controls start behind a quiet game HUD action');
assert.doesNotMatch(analysisSection, /class="analysis-section/, 'the old stacked analysis sections must be gone');

const navLabels = [...html.matchAll(/<span class="nav-label">([^<]+)<\/span>/g)].map(match => match[1]);
assert.deepEqual(navLabels, ['World', 'Dreams', 'Capture', 'Alarms', 'Settings']);
assert.match(serviceWorker, /\.\/analysis-state\.js/);

console.log('streamlined analysis screen contract tests passed');
