const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {firefox}=require('playwright');
const route=path.join(__dirname,'..','sketches','release-ui-overhaul','06-five-slot-badges');
const html=fs.readFileSync(path.join(route,'index.html'),'utf8');
const worker=fs.readFileSync(path.join(route,'service-worker.js'),'utf8');
const types={'.html':'text/html','.js':'text/javascript','.webmanifest':'application/manifest+json','.png':'image/png','.woff2':'font/woff2'};
const serve=()=>new Promise(resolve=>{const server=http.createServer((request,response)=>{try{const url=new URL(request.url,'http://127.0.0.1'),relative=decodeURIComponent(url.pathname).replace(/^\/+/,''),candidate=path.join(route,relative||'index.html');if(!candidate.startsWith(route+path.sep))throw new Error('invalid path');const stat=fs.statSync(candidate),file=stat.isDirectory()?path.join(candidate,'index.html'):candidate;response.setHeader('content-type',types[path.extname(file)]||'application/octet-stream');response.setHeader('cache-control','no-store');response.end(fs.readFileSync(file))}catch{response.statusCode=404;response.end('not found')}});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))});

test('Capture empty state uses the shared editorial card system and preserves both actions',()=>{assert.match(html,/<div class="capture-state capture-empty" data-log-state="empty"><div class="capture-empty-card">[\s\S]*?class="state-icon"[\s\S]*?<h2>Nothing to save today\.<\/h2>[\s\S]*?data-tab-target="history">Open History<\/button>[\s\S]*?id="remembered"[^>]*>I remembered something<\/button>/);assert.match(html,/\.capture-redesign \.capture-empty-card\{[^}]*max-width:342px[^}]*border-radius:28px[^}]*background:var\(--card\)/);assert.match(html,/\.capture-redesign \.capture-empty h2\{[^}]*font-family:"Newsreader",var\(--font-editorial\)[^}]*font-size:32px[^}]*font-weight:400/);assert.match(html,/\.capture-redesign \.capture-empty \.primary\{[^}]*max-width:280px[^}]*min-height:52px/);for(const hook of["document.getElementById('noDream').addEventListener('click',()=>showLogState('empty'))","document.getElementById('remembered').addEventListener('click',()=>showLogState('ready'))"])assert.ok(html.includes(hook))});

test('Capture empty redesign ships as a coupled v95 app shell',()=>{assert.match(html,/const APP_SHELL_VERSION='95'/);assert.match(worker,/const CACHE='dreamworld-pwa-20260830-95'/)});

test('Capture empty card fits short, narrow, and standard phones and both actions still navigate',async()=>{const {server,origin}=await serve();let browser;try{browser=await firefox.launch({headless:true});for(const viewport of[{width:331,height:568},{width:331,height:690},{width:390,height:844}])for(const theme of['light','dark']){const context=await browser.newContext({viewport,hasTouch:true,colorScheme:theme}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto(`${origin}/index.html?screen=log&theme=${theme}&empty-redesign=1`,{waitUntil:'networkidle'});await page.locator('#noDream').click();const primary=page.locator('[data-log-state="empty"] [data-tab-target="history"]');await page.keyboard.press('Tab');assert.equal(await primary.evaluate(node=>node===document.activeElement),true);const state=await page.evaluate(()=>{const screen=document.querySelector('[data-screen="log"]'),card=document.querySelector('.capture-empty-card').getBoundingClientRect(),nav=document.querySelector('.tabbar').getBoundingClientRect(),title=getComputedStyle(document.querySelector('.capture-empty h2')),focus=getComputedStyle(document.activeElement);return{active:document.querySelector('[data-log-state="empty"]').classList.contains('active'),overflow:screen.scrollWidth>screen.clientWidth,card:{left:card.left,right:card.right,top:card.top,bottom:card.bottom},navTop:nav.top,font:title.fontFamily,size:title.fontSize,weight:title.fontWeight,focus:{visible:document.activeElement.matches(':focus-visible'),width:focus.outlineWidth,offset:focus.outlineOffset,style:focus.outlineStyle}}});assert.equal(state.active,true);assert.equal(state.overflow,false);assert.ok(state.card.left>=15&&state.card.right<=viewport.width-15);assert.ok(state.card.bottom<=state.navTop-12,`empty card overlaps navigation at ${viewport.width}x${viewport.height}`);assert.match(state.font,/Newsreader/);assert.equal(state.size,viewport.height<=620?'28px':viewport.width<=350?'30px':'32px');assert.equal(state.weight,'400');assert.deepEqual(state.focus,{visible:true,width:'3px',offset:'3px',style:'solid'});await page.locator('#remembered').click();assert.equal(await page.locator('[data-log-state="ready"]').evaluate(node=>node.classList.contains('active')),true);await page.locator('#noDream').click();await primary.click();assert.equal(await page.locator('[data-screen="history"]').evaluate(node=>node.classList.contains('active')),true);assert.deepEqual(errors,[]);await context.close()}}finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}});
