const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {firefox}=require('playwright');
const route=path.join(__dirname,'..','sketches','release-ui-overhaul','06-five-slot-badges');
const types={'.html':'text/html','.js':'text/javascript','.webmanifest':'application/manifest+json','.png':'image/png','.woff2':'font/woff2'};
const serve=()=>new Promise(resolve=>{const server=http.createServer((request,response)=>{try{const url=new URL(request.url,'http://127.0.0.1'),relative=decodeURIComponent(url.pathname).replace(/^\/+/,''),candidate=path.join(route,relative||'index.html');if(!candidate.startsWith(route+path.sep))throw new Error('invalid path');const stat=fs.statSync(candidate),file=stat.isDirectory()?path.join(candidate,'index.html'):candidate;response.setHeader('content-type',types[path.extname(file)]||'application/octet-stream');response.setHeader('cache-control','no-store');response.end(fs.readFileSync(file))}catch{response.statusCode=404;response.end('not found')}});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))});

test('Insights reference hierarchy and real interactions hold across phone sizes and themes',async()=>{
 const {server,origin}=await serve();let browser;
 try{browser=await firefox.launch({headless:true});for(const viewport of[{width:390,height:844},{width:375,height:667}])for(const theme of['light','dark']){
  const context=await browser.newContext({viewport,hasTouch:true,colorScheme:theme});const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(String(error)));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
  await page.addInitScript(()=>{const RealDate=Date;class FixedDate extends RealDate{constructor(...args){super(...(args.length?args:['2026-08-26T14:00:00-07:00']))}static now(){return new RealDate('2026-08-26T14:00:00-07:00').getTime()}}window.Date=FixedDate});
  await page.goto(`${origin}/index.html?theme=${theme}&screen=insights&viewport-regression=1`,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);
  const layout=await page.evaluate(()=>{const screen=document.querySelector('[data-screen="insights"]'),latest=document.querySelector('.insights-latest-card'),patterns=document.querySelector('.insights-patterns'),calendar=document.querySelector('.insights-calendar'),days=[...document.querySelectorAll('.calendar-day')],metrics=[...document.querySelectorAll('.insight-metric')];return{classed:screen.classList.contains('insights-reference-remodel'),horizontalOverflow:screen.scrollWidth>screen.clientWidth+1,order:latest.compareDocumentPosition(patterns)&Node.DOCUMENT_POSITION_FOLLOWING&&patterns.compareDocumentPosition(calendar)&Node.DOCUMENT_POSITION_FOLLOWING,latestHeight:document.getElementById('latestDreamRail').getBoundingClientRect().height,latestExcerpt:document.getElementById('latestDreamRailExcerpt').textContent,dayMin:Math.min(...days.map(day=>day.getBoundingClientRect().height)),dayCount:days.length,hasDream:days.filter(day=>day.classList.contains('has-dream')).length,metricColumns:new Set(metrics.map(card=>Math.round(card.getBoundingClientRect().x))).size,values:{nights:document.getElementById('insightDreamNights').textContent,sleep:document.getElementById('insightAverageSleep').textContent,recording:document.getElementById('insightAverageDream').textContent,recall:document.getElementById('insightRecall').textContent}}});
  assert.deepEqual(errors,[]);assert.equal(layout.classed,true);assert.equal(layout.horizontalOverflow,false);assert.ok(layout.order);assert.ok(layout.latestHeight>=147.5);assert.ok(layout.latestExcerpt.length>20);assert.ok(layout.dayMin>=43.5);assert.equal(layout.dayCount,31);assert.equal(layout.hasDream,6);assert.equal(layout.metricColumns,2);assert.deepEqual(layout.values,{nights:'6',sleep:'7h 26m',recording:'1:14',recall:'4 of 6'});
  const latestTitle=await page.locator('#latestDreamRailTitle').textContent();await page.locator('#latestDreamRail').click();assert.equal(await page.locator('#historyFocusTitle').textContent(),latestTitle);assert.equal(await page.evaluate(()=>document.activeElement.id),'historyFocusTitle');await page.locator('#historyFocusBack').click();await page.locator('[data-tab="insights"]').click();
  const dreamDay=page.locator('.calendar-day.has-dream').first(),dreamLabel=await dreamDay.getAttribute('aria-label');await dreamDay.click();assert.equal(await page.locator('#historyFocus').isVisible(),true,`${dreamLabel} did not open its log`);await page.locator('#historyFocusBack').click();await page.locator('[data-tab="insights"]').click();
  const emptyDay=page.locator('.calendar-day:not(.has-dream)').first();await emptyDay.click();assert.equal(await page.locator('#insightDetailTitle').textContent(),'No dream entry for this day');
  await page.locator('.insights-disclosure').scrollIntoViewIfNeeded();const bottom=await page.evaluate(()=>{const disclosure=document.querySelector('.insights-disclosure').getBoundingClientRect(),tab=document.querySelector('.tabbar').getBoundingClientRect();return{disclosureBottom:disclosure.bottom,tabTop:tab.top}});assert.ok(bottom.disclosureBottom<=bottom.tabTop,`${theme} ${viewport.width} disclosure is obscured by navigation`);await context.close()
 }}finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}
});
