const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');
const {firefox}=require('playwright');
const route=path.join(__dirname,'..','sketches','release-ui-overhaul','06-five-slot-badges');
const types={'.html':'text/html','.js':'text/javascript','.webmanifest':'application/manifest+json','.png':'image/png','.woff2':'font/woff2'};
const serve=()=>new Promise(resolve=>{const server=http.createServer((request,response)=>{try{const url=new URL(request.url,'http://127.0.0.1'),relative=decodeURIComponent(url.pathname).replace(/^\/+/,''),candidate=path.join(route,relative||'index.html');if(!candidate.startsWith(route+path.sep))throw new Error('invalid path');const stat=fs.statSync(candidate),file=stat.isDirectory()?path.join(candidate,'index.html'):candidate;response.setHeader('content-type',types[path.extname(file)]||'application/octet-stream');response.setHeader('cache-control','no-store');response.end(fs.readFileSync(file))}catch{response.statusCode=404;response.end('not found')}});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))});

test('real recording controls drive reactive bars, ripple, pause, resume, and saved draft',async()=>{
 const {server,origin}=await serve();let browser;
 try{browser=await firefox.launch({headless:true});for(const colorScheme of ['light','dark']){const context=await browser.newContext({viewport:{width:331,height:690},hasTouch:true,colorScheme}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(String(error)));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
  await page.addInitScript(()=>{let phase=0;class FakeTrack{stop(){window.__trackStopped=true}}class FakeStream{getTracks(){return[new FakeTrack()]}}Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>new FakeStream()}});class FakeRecorder{constructor(stream,options={}){this.stream=stream;this.mimeType=options.mimeType||'audio/webm';this.state='inactive'}start(){this.state='recording'}pause(){this.state='paused'}resume(){this.state='recording'}stop(){this.state='inactive';this.ondataavailable?.({data:new Blob(['dream-audio'],{type:this.mimeType})});this.onstop?.()}}FakeRecorder.isTypeSupported=()=>true;window.MediaRecorder=FakeRecorder;class FakeAnalyser{set fftSize(value){this._fftSize=value}get fftSize(){return this._fftSize||512}disconnect(){}getByteTimeDomainData(samples){phase+=.31;for(let i=0;i<samples.length;i++)samples[i]=128+Math.round(Math.sin(i*.19+phase)*30)}}class FakeContext{constructor(){window.__contexts=(window.__contexts||0)+1}resume(){return Promise.resolve()}createAnalyser(){return new FakeAnalyser()}createMediaStreamSource(){return{connect(){},disconnect(){}}}close(){window.__closed=(window.__closed||0)+1;return Promise.resolve()}}window.AudioContext=FakeContext});
  await page.goto(`${origin}/index.html?screen=log&recording-animation-test=1`,{waitUntil:'networkidle'});await page.locator('#startRecording').click();await page.waitForSelector('.capture-recording.active[data-recording-state="recording"]');await page.waitForFunction(()=>document.getElementById('voiceVisual').dataset.reactive==='true'&&[...document.querySelectorAll('.recording-bar')].some(bar=>parseFloat(getComputedStyle(bar).transform.split(',')[3]||'0')>.2));const active=await page.evaluate(()=>({ripple:parseFloat(document.getElementById('voiceVisual').style.getPropertyValue('--ripple-scale')),bars:[...document.querySelectorAll('.recording-bar')].map(bar=>bar.style.transform),live:document.getElementById('recordingLiveLabel').textContent,status:document.getElementById('recordingStatus').textContent}));assert.ok(active.ripple>1);assert.ok(new Set(active.bars).size>3);assert.deepEqual([active.live,active.status],['Live','Recording']);
  await page.locator('#pauseRecording').click();await page.waitForSelector('.capture-recording[data-recording-state="paused"]');await page.waitForTimeout(220);const paused=await page.evaluate(()=>({label:document.getElementById('pauseRecordingLabel').textContent,live:document.getElementById('recordingLiveLabel').textContent,status:document.getElementById('recordingStatus').textContent,reactive:document.getElementById('voiceVisual').dataset.reactive,bars:[...document.querySelectorAll('.recording-bar')].map(bar=>bar.style.transform),core:getComputedStyle(document.querySelector('.recording-core')).backgroundColor,dot:getComputedStyle(document.querySelector('.recording-live-dot')).backgroundColor,closed:window.__closed}));assert.deepEqual([paused.label,paused.live,paused.status,paused.reactive],['Resume','Paused','Paused','false']);assert.deepEqual([paused.core,paused.dot],['rgb(170, 167, 159)','rgb(170, 167, 159)'],`${colorScheme} paused visual remains active`);assert.ok(paused.bars.every(value=>/^scaleY\((?:0?\.12)\)$/.test(value)));assert.ok(paused.closed>=1);
  await page.locator('#pauseRecording').click();await page.waitForFunction(()=>document.querySelector('.capture-recording').dataset.recordingState==='recording'&&document.getElementById('voiceVisual').dataset.reactive==='true');assert.deepEqual(await page.evaluate(()=>[document.getElementById('pauseRecordingLabel').textContent,document.getElementById('recordingLiveLabel').textContent]),['Pause','Live']);
  await page.locator('#stopRecording').click();await page.waitForSelector('.capture-draft.active');assert.equal(await page.locator('#draftTime').textContent().then(text=>/Stored on this iPhone|Available while this app stays open/.test(text)),true);assert.equal(await page.evaluate(()=>window.__trackStopped),true);assert.deepEqual(errors,[]);await context.close()}
 }finally{await browser?.close();await new Promise(resolve=>server.close(resolve))}
});
